### PR TITLE
Check for null

### PR DESCRIPTION
**Pull request by puncoz**
checking null to prevent "Parameter must be an array or an object that implements Countable" error in php v7.2+

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks. I have to ask though, what bug does this fix. This variable should never be null. I'm tempted to say that if it does end up null by mistake, then let it crash.

**Comment by puncoz** [comment]
Recently, after release of stable PHP v7.2, whenever some error occurred in laravel application, a php error "count(): Parameter must be an array or an object that implements Countable" appears instead of default error page.

**Comment by GrahamCampbell** [comment]
Are you using the very latest version of this package?

**Comment by GrahamCampbell** [comment]
V9.4 or V10.0 are required for PHP 7.2 support.

Correct me if I'm wrong, but I don't think this PR is needed. The problem lies with the fact that you are running a version of this package older than 9.4.0 or 10.0.0.

**Comment by puncoz** [comment]
I m using v10+, and rechecked everything with fresh setup, but problem still persist
image

**Comment by GrahamCampbell** [comment]
Could you please update the PR to prevent the variable from ever being null in the first place?

**Comment by puncoz** [comment]
sure, i'll go through the codebase, and update :)

**Pull request closed without merging**
