### PR TITLE
Indentification -> Identification

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. This technically need another major version bump.

**Comment by vinkla** [comment]
@GrahamCampbell can't you just retag?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
Meh, will just do a minor bump despite this breaking change.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
