### PR TITLE
Stuffs

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by younes0** [comment]
Works fine if error pages exists otherwise it displays as you know a json response:

``` json
{"errors":[{"id":"84feb47d-9293-4315-a369-d84e8eb8cb99","status":505,"title":"Internal Server Error","detail":"An error has occurred and this resource cannot be displayed."}]}
```

Why not keeping `return (new SymfonyDisplayer)->createResponse($e);` in case the view doesn't exist?

**Comment by GrahamCampbell** [comment]
Really? It should call back to the HtmlDisplayer surely?

**Comment by younes0** [comment]
Okay so I added the HtmlDisplayer after ViewDisplayer in displayers config
I think it's great. The HtmlDisplayer response is much more user-friendly than Symfony's one.
+1

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by GrahamCampbell** [comment]
Merging this. Will release v5.0.0 soonish, but probably not today.

**Comment by GrahamCampbell** [comment]
You can install it with `~5.0@dev`, or whatever for now. :)

**Comment by younes0** [comment]
Thanks for everything :)

**Comment by GrahamCampbell** [comment]
No problem. :)

**Pull request merged**
