### PR TITLE
Allow Symfony 5.0 dependencies 

### PR DESCRIPTION
**Pull request by prodigeris**
#SymfonyHackday

### CODE REVIEW

**Comment by rbaarsma** [comment]
In the it https://github.com/symfony/console/blob/master/CHANGELOG.md says:

```
renamed Application::renderException() and Application::doRenderException() to renderThrowable() and doRenderThrowable() respectively.
```

This bundle is using `renderException` in https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/ExceptionHandler.php#L135 --> I'm guessing this will no longer work, even though there seems to be no test for this

**Review by rbaarsma — CHANGES_REQUESTED** [review]
(see comment above)

**Comment by GrahamCampbell** [comment]
Thanks for the PR. This package is currently only for Laravel 5 and 6, which do not support Symfony 5.x, so there is no need for any changes just yet.

**Comment by GrahamCampbell** [comment]
I will address Laravel 7 + Symfony 5 in February next year, closer to the release. Laravel 6 will never support Symfony 5, so there is no rush here.

**Comment by GrahamCampbell** [comment]
@rbaarsma Thanks for the heads up about the renamed method. I'll look in full detail into what needs to change when I look into updating this package for Laravel 7 in Q1 2020. :)

**Pull request closed without merging**
